# Generated by Django 3.2.5 on 2021-07-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Category Name')),
                ('icon', models.ImageField(upload_to=None, verbose_name='Avatar')),
                ('description', models.TextField()),
            ],
        ),
    ]
