# Generated by Django 3.2.5 on 2021-07-22 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_industry'),
        ('accounts', '0006_auto_20210722_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to='profile/', verbose_name='Avatar'),
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50, verbose_name='Company name')),
                ('about', models.TextField()),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('avatar', models.ImageField(upload_to='company/logo/', verbose_name='Company Logo')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Linkedin Link')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Linkedin Link')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Linkedin Link')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Linkedin Link')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Linkedin Link')),
                ('industry', models.ManyToManyField(to='dashboard.Industry')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='advister')),
            ],
            options={
                'verbose_name': 'CompanyProfile',
                'verbose_name_plural': 'CompanyProfiles',
            },
        ),
    ]
