# Generated by Django 3.2.5 on 2021-07-27 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_industry'),
        ('accounts', '0008_auto_20210726_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='industry',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.industry'),
        ),
    ]
