# Generated by Django 3.2.5 on 2021-07-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210727_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='images/resource/candidate-1.png', upload_to='profile/', verbose_name='Avatar'),
        ),
    ]
