# Generated by Django 3.2.5 on 2021-07-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='candidate-1.png', upload_to='profile/', verbose_name='Avatar'),
        ),
    ]
