# Generated by Django 3.2.5 on 2021-07-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0003_auto_20210722_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='is_saved',
            field=models.BooleanField(default=False, editable=False, verbose_name='archived'),
        ),
    ]
