# Generated by Django 3.2.5 on 2021-07-28 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opportunity', '0004_opportunity_is_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active / ready'),
        ),
        migrations.CreateModel(
            name='AppliedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved', models.BooleanField(verbose_name='Saved')),
                ('applied', models.DateField(verbose_name='Start Date')),
                ('applying', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Person Applying')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunity.opportunity', verbose_name='Opportunity')),
            ],
            options={
                'verbose_name': 'Applied Job',
                'verbose_name_plural': 'Applied Jobs',
            },
        ),
    ]
