# Generated by Django 3.2.5 on 2021-07-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0005_auto_20210728_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjob',
            name='saved',
            field=models.BooleanField(default=False, verbose_name='Saved'),
        ),
    ]
