# Generated by Django 3.2.5 on 2021-07-28 16:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0006_alter_appliedjob_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjob',
            name='applied_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 28, 16, 46, 39, 364361, tzinfo=utc), verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='applied',
            field=models.BooleanField(default=False, verbose_name='Applied'),
        ),
    ]
