# Generated by Django 3.2.5 on 2021-09-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='cover',
            field=models.ImageField(help_text='image should be squared', upload_to='covers'),
        ),
    ]
